#!/usr/bin/env python3
"""mytools - a small reimplementation of a subset of bedtools."""

import sys

VERSION = "0.1.0"

USAGE = "usage: mytools --version"


def main(argv):
    if argv == ["--version"]:
        print(f"mytools {VERSION}")
        return 0
    print(USAGE, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
